#Support for MSDOS- Adapted from eCos.cmake
#Most of this stuff (especially angle-bracket variables) is not documented.
#Source: http://stackoverflow.com/questions/13415222/variables-with-angle-brackets-in-cmake-scripts
#Reference: http://www.cmake.org/Wiki/CMake_Useful_Variables/Get_Variables_From_CMake_Dashboards

# Guard against multiple inclusion, which e.g. leads to multiple calls to add_definition() #12987
IF(__MSDOS_CMAKE_INCLUDED)
  RETURN()
ENDIF()
SET(__MSDOS_CMAKE_INCLUDED TRUE)

IF(CMAKE_VERBOSE_MAKEFILE)
  SET(CMAKE_WCL_QUIET)
  SET(CMAKE_WLINK_QUIET)
  SET(CMAKE_LIB_QUIET)
ELSE(CMAKE_VERBOSE_MAKEFILE)
  SET(CMAKE_WCL_QUIET "-zq")
  SET(CMAKE_WLINK_QUIET "option quiet")
  SET(CMAKE_LIB_QUIET "-q")
ENDIF(CMAKE_VERBOSE_MAKEFILE)

#No shared Libraries on MSDOS
SET(CMAKE_SHARED_LIBRARY_C_FLAGS "")            # -pic
SET(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "")       # -shared
SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")         # +s, flag for exe link to use shared lib
SET(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG "")       # -rpath
SET(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP "")   # : or empty

SET(CMAKE_LINK_LIBRARY_SUFFIX "")
SET(CMAKE_STATIC_LIBRARY_PREFIX "")
SET(CMAKE_STATIC_LIBRARY_SUFFIX ".lib")
SET(CMAKE_SHARED_LIBRARY_PREFIX "")
SET(CMAKE_SHARED_LIBRARY_SUFFIX "")
SET(CMAKE_EXECUTABLE_SUFFIX ".EXE")
SET(CMAKE_DL_LIBS "" )


SET(CMAKE_FIND_LIBRARY_PREFIXES "")
SET(CMAKE_FIND_LIBRARY_SUFFIXES "lib")

#Can't say I'm certain what the following line does, but including it anyway
GET_PROPERTY(_IN_TC GLOBAL PROPERTY IN_TRY_COMPILE)
#message(${CMAKE_C_COMPILER_ID})
IF(CMAKE_C_COMPILER AND NOT  "${CMAKE_C_COMPILER_ID}" MATCHES "Watcom" AND NOT _IN_TC)
  MESSAGE(FATAL_ERROR "OpenWatcom WCL is currently required for MSDOS")
ENDIF(CMAKE_C_COMPILER AND NOT  "${CMAKE_C_COMPILER_ID}" MATCHES "Watcom" AND NOT _IN_TC)
IF(CMAKE_CXX_COMPILER AND NOT  "${CMAKE_CXX_COMPILER_ID}" MATCHES "Watcom" AND NOT _IN_TC)
  MESSAGE(FATAL_ERROR "OpenWatcom WCL is currently required for MSDOS")
ENDIF(CMAKE_CXX_COMPILER AND NOT  "${CMAKE_CXX_COMPILER_ID}" MATCHES "Watcom" AND NOT _IN_TC)


#Add IF("${CMAKE_C_COMPILER_ID}" MATCHES "WATCOM") later...
SET(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <FLAGS> -fo=\"<OBJECT>\" -c <SOURCE>")
SET(CMAKE_C_LINK_EXECUTABLE  "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -fo=<TARGET>") 
SET(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> <FLAGS> -fo=\"<OBJECT>\" -c <SOURCE>")
SET(CMAKE_CXX_LINK_EXECUTABLE  "<CMAKE_CXX_COMPILER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -fo=<TARGET>") 

#SET(CMAKE_C_LINK_EXECUTABLE
#    "wlink ${CMAKE_START_TEMP_FILE} ${CMAKE_WLINK_QUIET} name '<TARGET_UNQUOTED>' <LINK_FLAGS> option caseexact file {<OBJECTS>} <LINK_LIBRARIES> ${CMAKE_END_TEMP_FILE}")
    
#SET(CMAKE_CXX_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})

#-nostdlib -nostartfiles -L${ECOS_LIBTARGET_DIRECTORY} -Ttarget.ld  <LINK_LIBRARIES>")

SET(CMAKE_C_LINK_EXECUTABLE    "<CMAKE_C_COMPILER>   <FLAGS> <CMAKE_C_LINK_FLAGS>   <LINK_FLAGS> <OBJECTS> -fo=<TARGET>") 
#-nostdlib -nostartfiles -L${ECOS_LIBTARGET_DIRECTORY} -Ttarget.ld  <LINK_LIBRARIES>")
