#TARGETS SConscript
#Get settings.py values to determine the target. Use platform as well.

import os
Import('default_env')
#env = Environment(tools = ['mingw'], toolpath = ['.'])
#env = default_env.Clone(tools = ['mingw'], toolpath = ['.'])
env = Environment(tools = ['default', 'dos'], toolpath = ['.'])
Export('env')
